# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 323d6c37fe32f123903059a665efaf7e9d8b3b0257ba82cb641abfb0c04a3df5f6b74d910fd43deee90ebf584b458422b3231ce8f0ce18c243e21c52930e1f63

test:
  secret_key_base: 662ffb6d0304b63432081ce6e76a8d702d00c359ec1e0849b28cacd2444c9977c0107bd1bdeddfbe73c3c1fa5958a2cda1364a170ae1928754c270978470ec9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
